"""Writes graph :class:`Operation` streams to Neo4j — or to a .cypher script.

Three modes, chosen at construction:

* **push**  (default): execute operations against Neo4j in batched write
  transactions.
* **emit**  (``emit_path=...``): serialize operations to a replayable
  ``.cypher`` file. No database connection is opened.
* **dry-run** (``dry_run=True``): count operations only. No connection, no file.

Emit / dry-run modes let you exercise the full ingestion pipeline (and inspect
exactly what would be written) without a running Neo4j instance.
"""
from __future__ import annotations

import logging
from collections.abc import Iterable
from pathlib import Path
from typing import Any

from .config import Neo4jSettings
from .cypher import Operation

log = logging.getLogger("graphforge.writer")

try:  # progress bar is optional
    from tqdm import tqdm
except ImportError:  # pragma: no cover
    def tqdm(it, **_kwargs):  # type: ignore
        return it


class Neo4jWriter:
    def __init__(
        self,
        settings: Neo4jSettings,
        emit_path: str | None = None,
        dry_run: bool = False,
    ):
        self.settings = settings
        self.emit_path = emit_path
        self.dry_run = dry_run
        self._driver = None
        self._emit_fh = None
        self.ops_written = 0

        if self.emit_path:
            self._emit_fh = open(self.emit_path, "w", encoding="utf-8")  # noqa: SIM115  # long-lived emit handle, closed in close()
            self._emit_fh.write("// Generated by graphforge — replay with cypher-shell or Neo4j Browser\n\n")

    # -- lifecycle ---------------------------------------------------------
    @property
    def mode(self) -> str:
        if self.emit_path:
            return "emit"
        if self.dry_run:
            return "dry-run"
        return "push"

    def _driver_connect(self):
        if self._driver is None:
            self.settings.check_connectable()
            from neo4j import GraphDatabase  # lazy import

            self._driver = GraphDatabase.driver(
                self.settings.uri, auth=(self.settings.user, self.settings.password)
            )
            self._driver.verify_connectivity()
            log.info("Connected to Neo4j at %s (database=%s)", self.settings.uri, self.settings.database)
        return self._driver

    def __enter__(self) -> Neo4jWriter:
        return self

    def __exit__(self, *exc) -> None:
        self.close()

    def close(self) -> None:
        if self._driver is not None:
            self._driver.close()
            self._driver = None
        if self._emit_fh is not None:
            self._emit_fh.write("\n// End of script\n")
            self._emit_fh.close()
            self._emit_fh = None

    # -- schema ------------------------------------------------------------
    def apply_schema(self, cypher_text: str) -> int:
        """Run each statement in a schema block (constraints / indexes)."""
        statements = [s.strip() for s in _split_statements(cypher_text) if s.strip()]
        if self.emit_path:
            assert self._emit_fh is not None
            for stmt in statements:
                self._emit_fh.write(stmt + ";\n")
            self._emit_fh.write("\n")
            return len(statements)
        if self.dry_run:
            return len(statements)
        driver = self._driver_connect()
        with driver.session(database=self.settings.database) as session:
            for stmt in statements:
                session.run(stmt)
        return len(statements)

    # -- operations --------------------------------------------------------
    def write(self, ops: Iterable[Operation], desc: str = "writing", *,
              progress: bool = True) -> int:
        """Write ``ops``, batched. ``progress=False`` suppresses this call's bar.

        Callers that write in a loop should own a single bar over the loop and
        pass ``progress=False``: one bar per call means one bar *per file* during
        a repository ingest, which prints thousands of them.
        """
        ops = list(ops)
        if not ops:
            return 0

        if self.emit_path:
            assert self._emit_fh is not None
            for op in ops:
                self._emit_fh.write(op.to_script() + "\n")
            self.ops_written += len(ops)
            return len(ops)

        if self.dry_run:
            self.ops_written += len(ops)
            return len(ops)

        driver = self._driver_connect()
        batch_size = max(1, self.settings.batch_size)
        starts = range(0, len(ops), batch_size)
        with driver.session(database=self.settings.database) as session:
            for start in (tqdm(starts, desc=desc, unit="batch") if progress else starts):
                batch = ops[start : start + batch_size]
                session.execute_write(_run_batch, batch)
        self.ops_written += len(ops)
        return len(ops)

    def run_statements(self, statements: list[str], desc: str = "executing") -> int:
        """Run literal Cypher statements in autocommit mode.

        Unlike :meth:`write`, this does not wrap statements in an explicit
        transaction, so ``CALL { ... } IN TRANSACTIONS`` (used for large batched
        deletes) is permitted.
        """
        statements = [s for s in statements if s and s.strip()]
        if not statements:
            return 0
        if self.emit_path:
            assert self._emit_fh is not None
            for stmt in statements:
                self._emit_fh.write(stmt.rstrip(";") + ";\n")
            self._emit_fh.write("\n")
            self.ops_written += len(statements)
            return len(statements)
        if self.dry_run:
            self.ops_written += len(statements)
            return len(statements)
        driver = self._driver_connect()
        with driver.session(database=self.settings.database) as session:
            for stmt in tqdm(statements, desc=desc, unit="stmt"):
                session.run(stmt)
        self.ops_written += len(statements)
        return len(statements)

    # -- introspection -----------------------------------------------------
    def repository_status(self) -> list[dict[str, Any]]:
        """Return per-repository ingest status (push mode only)."""
        if self.mode != "push":
            return []
        driver = self._driver_connect()
        with driver.session(database=self.settings.database) as session:
            return [
                r.data() for r in session.run(
                    "MATCH (r:Repository) RETURN r.name AS name, r.status AS status, "
                    "r.files AS files, r.commits AS commits, r.lastIngestedAt AS lastIngestedAt "
                    "ORDER BY r.name"
                )
            ]

    def label_counts(self) -> dict[str, int]:
        """Return node counts per label (push mode only)."""
        if self.mode != "push":
            return {}
        driver = self._driver_connect()
        counts: dict[str, int] = {}
        with driver.session(database=self.settings.database) as session:
            labels = [r["label"] for r in session.run("CALL db.labels() YIELD label RETURN label")]
            for label in labels:
                rec = session.run(f"MATCH (n:`{label}`) RETURN count(n) AS c").single()
                counts[label] = rec["c"] if rec else 0
        return counts


def _run_batch(tx, batch: list[Operation]) -> None:
    for op in batch:
        tx.run(op.cypher, op.params)


def _split_statements(text: str) -> list[str]:
    """Split a Cypher script on semicolons, ignoring those inside strings and comments."""
    statements: list[str] = []
    buf: list[str] = []
    in_squote = in_dquote = in_line_comment = False
    i = 0
    while i < len(text):
        ch = text[i]
        nxt = text[i + 1] if i + 1 < len(text) else ""
        if in_line_comment:
            buf.append(ch)
            if ch == "\n":
                in_line_comment = False
            i += 1
            continue
        if not in_squote and not in_dquote and ch == "/" and nxt == "/":
            in_line_comment = True
            buf.append(ch)
            i += 1
            continue
        if ch == "'" and not in_dquote:
            in_squote = not in_squote
        elif ch == '"' and not in_squote:
            in_dquote = not in_dquote
        if ch == ";" and not in_squote and not in_dquote:
            statements.append("".join(buf))
            buf = []
            i += 1
            continue
        buf.append(ch)
        i += 1
    if "".join(buf).strip():
        statements.append("".join(buf))
    return statements


def load_schema(name: str) -> str:
    """Read a bundled schema file from graphforge/schema/."""
    path = Path(__file__).resolve().parent.parent / "schema" / name
    return path.read_text(encoding="utf-8")
